version: '3.3'
services:
  claim-accept:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'claim-accept'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'admin'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-claim-accept:/var/lib/mysql
  claim-prod:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'claim-prod'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'admin'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3307 on the container
      - '3307'
      # Where our data will be persisted
    volumes:
      - my-claim-prod:/var/lib/mysql
# Names our volume
volumes:
  my-claim-accept:
  my-claim-prod: